build_script:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GitHubPersonalAccessToken):x-oauth-basic@github.com`n"
  - git config --global user.email "wekempf@outlook.com"
  - git config --global user.name "AppVeyor Build Service"
  - ps: .\build.ps1

test: off

branches:
  only:
    - master
      
# Do not build on tags
skip_tags: true

environment:
  GitHubPersonalAccessToken:
    secure: BapiM5BN8CJwmX6mPMGkxkD3lq9soxMAdCPzpCj9pM+GuY3PgITquBkJRGk/dPmR
