build_script:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GitHubPersonalAccessToken):x-oauth-basic@github.com`n"
  - git config --global user.email "wekempf@outlook.com"
  - git config --global user.name "AppVeyor Build Service"
  - ps: .\build.ps1

test: off

branches:
  only:
    - develop
    - master
    - /release\/.*/
      
# Do not build on tags
skip_tags: true

clone_folder: c:\projects\testify

environment:
  GitHubPersonalAccessToken:
    secure: H9H2HNKz0vEz91m6b5aEoEeb3xhrI3rbsJKvmbkQFbwq0P+zqhoPdcx4EBqNbvYl
  CoverallsToken:
    secure: uCTsfs+WNEYvAjp8jZ8CLqfNe2JsKvOCDIXdIFsNovbvcrvHzt7J+yZdvi4w+h6y
  NuGetApiKey:
    secure: WCC9YoXjXGB6om2aN3jD0n5Jk63LKg42sViodxTK04T16/MQ0e4F8JU2XmoO+iY6
  MyGetApiKey:
    secure: 3bjCk3g3eDsa72b1jJR9QRWK+iivJLfcNVBV/fVJChIwtBdZxTKOrBZxhOHU5jR/

artifacts:
  - path: 'docs\site.zip'
